name: butterfree
description: A Visual Editor Tool for stateless Flutter widgets.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  analyzer: ^0.34.0
  dart_style: ^1.2.3
  path: ^1.6.2
  file_chooser:
    path: ../plugins/file_chooser

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true